name: terraform plan

on:
  pull_request:
    branches: [master]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./app"

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./app"

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./app"

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./app"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./app"